### ISSUE TITLE
Build error when trying to run the Android version

### ISSUE THREAD

**Issue by erf** [rohan20/flutter-facebook-auth#2]
```
Finished with error: ProcessException: Process "/Users/erlend/Library/Android/sdk/platform-tools/adb" exited abnormally:
Starting: Intent { act=android.intent.action.RUN flg=0x20000000 cmp=com.example.facebookauth/com.facebook.FacebookActivity (has extras) }

Security exception: Permission Denial: starting Intent { act=android.intent.action.RUN flg=0x30000000 cmp=com.example.facebookauth/com.facebook.FacebookActivity (has extras) } from null (pid=9542, uid=2000) not exported from uid 10086

java.lang.SecurityException: Permission Denial: starting Intent { act=android.intent.action.RUN flg=0x30000000 cmp=com.example.facebookauth/com.facebook.FacebookActivity (has extras) } from null (pid=9542, uid=2000) not exported from uid 10086
	at com.android.server.am.ActivityStackSupervisor.checkStartAnyActivityPermission(ActivityStackSupervisor.java:1788)
	at com.android.server.am.ActivityStarter.startActivity(ActivityStarter.java:717)
	at com.android.server.am.ActivityStarter.startActivity(ActivityStarter.java:544)
	at com.android.server.am.ActivityStarter.startActivityMayWait(ActivityStarter.java:1099)
	at com.android.server.am.ActivityStarter.execute(ActivityStarter.java:486)
	at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:5120)
	at com.android.server.am.ActivityManagerService.startActivityAsUser(ActivityManagerService.java:5094)
	at com.android.server.am.ActivityManagerShellCommand.runStartActivity(ActivityManagerShellCommand.java:479)
	at com.android.server.am.ActivityManagerShellCommand.onCommand(ActivityManagerShellCommand.java:161)
	at android.os.ShellCommand.exec(ShellCommand.java:103)
	at com.android.server.am.ActivityManagerService.onShellCommand(ActivityManagerService.java:16005)
	at android.os.Binder.shellCommand(Binder.java:634)
	at android.os.Binder.onTransact(Binder.java:532)
	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:3592)
	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3291)
	at android.os.Binder.execTransact(Binder.java:731)
  Command: /Users/erlend/Library/Android/sdk/platform-tools/adb -s emulator-5554 shell am start -a android.intent.action.RUN -f 0x20000000 --ez enable-background-compilation true --ez enable-dart-profiling true --ez enable-checked-mode true --ez start-paused true com.example.facebookauth/com.facebook.FacebookActivity
```

**Comment by erf** [comment]
Output from `flutter doctor -v`:

```
[✓] Flutter (Channel beta, v0.11.13, on Mac OS X 10.14.1 18B75, locale en-NO)
    • Flutter version 0.11.13 at /Users/erlend/flutter
    • Framework revision 58c8489fcd (3 days ago), 2018-11-29 19:20:18 -0500
    • Engine revision 7375a0f414
    • Dart version 2.1.0 (build 2.1.0-dev.9.4 f9ebf21297)

[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
    • Android SDK at /Users/erlend/Library/Android/sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-28, build-tools 28.0.3
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)
    • All Android licenses accepted.

[✓] iOS toolchain - develop for iOS devices (Xcode 10.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 10.1, Build version 10B61
    • ios-deploy 2.0.0
    • CocoaPods version 1.6.0.beta.1

[✓] Android Studio (version 3.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 31.1.1
    • Dart plugin version 181.5656
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1136-b06)

[✓] Connected device (2 available)
    • Android SDK built for x86 • emulator-5554                        • android-x86 • Android 9
      (API 28) (emulator)
    • iPhone XR                 • 4F1F4012-EB5B-4344-91C5-198E800673C6 • ios         • iOS 12.1
      (simulator)

• No issues found!
```

**Comment by erf** [comment]
I will look into using the official plugin instead at https://pub.dartlang.org/packages/firebase_auth
