### ISSUE TITLE
The SDK has not been initialized

### ISSUE THREAD

**Issue by IvanTerrito** [rohan20/flutter-facebook-auth#3]
Hello i followed instruction in Medium's article but when I start the app it crashes (i used the plugin in home page).
I setted facebook project to use my correct package and this class: `app.roving.MainActivity`

Thanks in advance!

Here is the error:
`java.lang.RuntimeException: Unable to start activity ComponentInfo{app.roving/app.roving.MainActivity}: The SDK has not been initialized, make sure to call FacebookSdk.sdkInitialize() first.
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2957)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
     Caused by: The SDK has not been initialized, make sure to call FacebookSdk.sdkInitialize() first.
        at com.facebook.internal.Validate.sdkInitialized(Validate.java:144)
        at com.facebook.login.LoginManager.<init>(LoginManager.java:80)
        at com.facebook.login.LoginManager.getInstance(LoginManager.java:93)
        at com.roughike.facebooklogin.facebooklogin.FacebookLoginPlugin$FacebookSignInDelegate.<init>(FacebookLoginPlugin.java:109)
        at com.roughike.facebooklogin.facebooklogin.FacebookLoginPlugin.<init>(FacebookLoginPlugin.java:38)
        at com.roughike.facebooklogin.facebooklogin.FacebookLoginPlugin.registerWith(FacebookLoginPlugin.java:42)
        at io.flutter.plugins.GeneratedPluginRegistrant.registerWith(GeneratedPluginRegistrant.java:14)
        at app.roving.MainActivity.onCreate(MainActivity.java:11)`

**Comment by sumitrvi** [comment]
@IvanTerrito HI,Have you got any solution of this issue
